x = input('digite algo: ')
print('É do tipo', type(x))
print('É alfanumérico? ', x.isalnum())
print('É alfabetico? ', x.isalpha())
print('É minúsculo? ', x.islower())
print('É numérico? ', x.isnumeric())
print('É espaço? ', x.isspace())
print('É Maiscúlo? ', x.isupper())
print('É capitalizada? ', x.istitle())