print('Para saber a média dos alunos digite as quatros notas ou menos')
n1 = float(input('Primeira nota: '))
n2 = float(input('Segunda nota: '))
n3 = float(input('Terceira nota: '))
n4 = float(input('Quarta nota: '))
print('Sua média é {:.1f}'.format((n1 + n2 +n3 +n4) / 4))
